name: CI - Ionic WEB - Action on Commit

on:
    push:
        branches: [ main, feature ]
    pull_request:
        branches: [ main ]

jobs:
    verificacion-en-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del codigo
              uses: actions/checkout@v4

            - name: Configuracion de Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '24'
                cache: 'npm'
                cache-dependency-path: 'ops_dc/package-lock.json'

            - name: Instalacion de Dependencias del proyecto
              run: npm ci
              working-directory: './ops_dc'